export const ADD_FIELD = 'ADD_FIELD';
export const REMOVE_FIELD = 'REMOVE_FIELD';
export const CHANGE_FIELD_NAME = 'CHANGE_FIELD_NAME';
export const TOGGLE_FIELD_REQUIRED = 'TOGGLE_FIELD_REQUIRED';

export const ADD_FIELD_OPTION = 'ADD_FIELD_OPTION';
export const REMOVE_FIELD_OPTION = 'REMOVE_FIELD_OPTION';
export const CHANGE_FIELD_OPTION_NAME = 'CHANGE_FIELD_OPTION_NAME';

export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION';
export const SAVE_STATUS = 'SAVE_STATUS';
